[target.x86_64-unknown-linux-gnu.foo]
rustc-link-lib = ["foo"]
rustc-link-search = ["/path/to/foo"]
rustc-flags = "-L /some/path"
rustc-cfg = ['key="value"']
rustc-env = {'key = "value"}
rustc-cdylib-link-arg = ["â€¦"]
metadata_key1 = "value"
metadata_key2 = "value"
[dependencies]
mio = "1"
