[build]
rustc-wrapper = "/path/to/sccache"
[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]
[package]
name = "hello_world"
version = "0.1.0"
edition = "2024"

[dependencies]
